### PR TITLE
Add build and packaging script

### PR DESCRIPTION
**Pull request by Wilgnne**
### Addition of production build scripts

These scripts are the basis for packaging the project in an executable

### CODE REVIEW

**Comment by Wilgnne** [comment]
To build the executable, an `index.js` script is needed to be the entry point for electron, otherwise a `package.json` must be present in the dist folder to indicate the entry point. 
Which approach would be better, renaming `electron/main.ts` to `electron/index.ts` or generating a `package.json` at compile time?

**Comment by diego3g** [comment]
I think that we should use the same folder from development, `dist`, so we don't need to change package.json. What you think about it?

**Comment by Wilgnne** [comment]
I agree with the use of a `dist`, it will be necessary to include the files that are sent to the bundle in the `package.json`

```js
"build": {
  "appId": "your.id",
  "mac": {
    "category": "public.app-category.video"
  },
  "files": [
    "package.json"
    "dist/*",
  ]
}
```

**Comment by diego3g** [comment]
@Wilgnne can you add that on this PR?

**Comment by Wilgnne** [comment]
ok, i will rename the RP to include the packaging script

**Pull request merged**
